//go:build !genz
// Code generated by genz codez-matchers. DO NOT EDIT.

package codez

import (
)

// ArrayType

// BadExpr

// BasicLit

// BinaryExpr

// CallExpr

// ChanType

// CompositeLit

// Ellipsis

// FuncLit

// FuncType

// Ident

// IndexExpr

// IndexListExpr

// InterfaceType

// KeyValueExpr

// MapType

// ParenExpr

// SelectorExpr

// SliceExpr

// StarExpr

// StructType

// TypeAssertExpr

// UnaryExpr

