#!/bin/bash
set -eo pipefail

ztarget_dir="${PROJECT_ROOT}/../ztarget"

task_all() {
    find . -name go.mod -execdir bash -c "$*" \;
}

task_testall() {
    find . -name go.mod -execdir go test "$@" ./... \;
}

task_pkgall() {
    go run "${PROJECT_ROOT}/zscripts/ezrun" pkg --all
    task_ztarget_finalize
}

task_ztarget() {
    find "$ztarget_dir" -name go.local.mod -execdir bash -c "$*" \;
}

task_ztarget_finalize() {
    find "$ztarget_dir" -name go.local.mod -execdir bash -c '
go get  -modfile=go.local.mod ./...
go test -modfile=go.local.mod ./...
cat go.local.mod | grep -v "replace ezpkg\.io" > go.mod
' bash {} +
}

source "${PROJECT_ROOT}/zscripts/_run.sh"
