#!/bin/bash
set -eo pipefail

ZTARGET_DIR="${EZPKG_ROOT_DIR}/ztarget"

task_all() {
    find $EZPKG_DIR/*z -name go.mod -execdir bash -c "
export PKGNAME=\$(basename \$PWD)
echo 👉 \$PWD
$*
" \;
}

task_testall() {
    find $EZPKG_DIR/*z -name go.mod -execdir go test "$@" ./... \;
}

task_pkgall() {
    go run "${EZPKG_DIR}/zscripts/ezrun" pkg --all
    task_ztarget_finalize
}

task_ztarget() {
    find "$ZTARGET_DIR" -name go.local.mod -execdir bash -c "
export PKGNAME=\$(basename \$PWD)
echo 👉 \$PWD
$*
" \;
}

task_ztarget_finalize() {
    find "$ZTARGET_DIR" -name go.local.mod -execdir bash -c "
echo 👉 \$PWD
go get  -modfile=go.local.mod ./...
go test -modfile=go.local.mod ./...
cat go.local.mod | grep -v \"replace ezpkg\.io\" > go.mod
" bash {} +
}

source "${EZPKG_DIR}/zscripts/_run.sh"
