#!/bin/bash
set -eo pipefail

ZTARGET_DIR="${EZPKG_ROOT_DIR}/ztarget"

task_godoc() {
    if ! which godoc; then
        go install golang.org/x/tools/cmd/godoc
    fi
    printf "👉 http://localhost:6060/pkg/ezpkg.io/-/ezpkg\n\n"
    godoc -http=:6060
}

task_all() {
    find $EZPKG_DIR/*z -name go.mod -execdir bash -c "
export PKGNAME=\$(basename \$PWD)
echo 👉 \$PWD
$*
" \;
}

task_list() {
    go run "${EZPKG_DIR}/zscripts/ezrun" list "$@"
}

task_testall() {
    find $EZPKG_DIR/*z -name go.mod -execdir go test "$@" ./... \;
}

task_docall() {
    go run "${EZPKG_DIR}/zscripts/ezrun" doc --all
}

task_pkgall() {
    go run "${EZPKG_DIR}/zscripts/ezrun" doc --all
    go run "${EZPKG_DIR}/zscripts/ezrun" pkg --all
    task_ztarget_finalize
}

task_ztarget() {
    find "$ZTARGET_DIR" -name go.local.mod -execdir bash -c "
export PKGNAME=\$(basename \$PWD)
echo 👉 \$PWD
$*
" \;
}

task_ztarget_finalize() {
    find "$ZTARGET_DIR" -name go.local.mod -execdir bash -c "
echo 👉 \$PWD
go get  -modfile=go.local.mod ./...
go test -modfile=go.local.mod ./...
cat go.local.mod | grep -v \"replace ezpkg\.io\" > go.mod
" bash {} +
}

source "${EZPKG_DIR}/zscripts/_run.sh"
