#!/bin/bash
set -eo pipefail

task_colors() {
    color(){
        for c; do
            printf '\e[48;5;%dm %03d ' $c $c
        done
        printf '\e[0m \n'
    }

    IFS=$' \t\n'
    color {0..15}
    for ((i=0;i<6;i++)); do
        color $(seq $((i*36+16)) $((i*36+51)))
    done
    color {232..255}
}

task_true_colors() {
    # https://github.com/termstandard/colors
    awk 'BEGIN{
        s="⏺⏺⏺⏺⏺⏺⏺⏺⏺⏺⏺⏺⏺⏺⏺"; s=s s s s s s s s;
        for (colnum = 0; colnum<77; colnum++) {
            r = 255-(colnum*255/76);
            g = (colnum*510/76);
            b = (colnum*255/76);
            if (g>255) g = 510-g;
            printf "\x1b[48;2;%d;%d;%dm", r,g,b;
            printf "\x1b[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            printf "%s\x1b[0m", substr(s,colnum+1,1);
        }
        printf "\n";
    }'
}

source "${REPO_ROOT}/zscripts/_run.sh"
