//go:build !genz

// Code generated by genz codez-matchers. DO NOT EDIT.

package codez

import (
	ast "go/ast"
	token "go/token"
)

// AssignStmt
type zAssignStmtMatcher struct {
	_ *ast.AssignStmt

	Lhs    ExprListMatcher
	TokPos token.Pos
	Tok    token.Token
	Rhs    ExprListMatcher
}

// BadStmt
type zBadStmtMatcher struct {
	_ *ast.BadStmt

	From token.Pos
	To   token.Pos
}

// BlockStmt
type zBlockStmtMatcher struct {
	_ *ast.BlockStmt

	Lbrace token.Pos
	List   StmtListMatcher
	Rbrace token.Pos
}

// BranchStmt
type zBranchStmtMatcher struct {
	_ *ast.BranchStmt

	TokPos token.Pos
	Tok    token.Token
	Label  IdentMatcher
}

// CaseClause
type zCaseClauseMatcher struct {
	_ *ast.CaseClause

	Case  token.Pos
	List  ExprListMatcher
	Colon token.Pos
	Body  StmtListMatcher
}

// CommClause
type zCommClauseMatcher struct {
	_ *ast.CommClause

	Case  token.Pos
	Comm  StmtMatcher
	Colon token.Pos
	Body  StmtListMatcher
}

// DeclStmt
type zDeclStmtMatcher struct {
	_ *ast.DeclStmt

	Decl DeclMatcher
}

// DeferStmt
type zDeferStmtMatcher struct {
	_ *ast.DeferStmt

	Defer token.Pos
	Call  CallExprMatcher
}

// EmptyStmt
type zEmptyStmtMatcher struct {
	_ *ast.EmptyStmt

	Semicolon token.Pos
	Implicit  BoolMatcher
}

// ExprStmt
type zExprStmtMatcher struct {
	_ *ast.ExprStmt

	X ExprMatcher
}

// ForStmt
type zForStmtMatcher struct {
	_ *ast.ForStmt

	For  token.Pos
	Init StmtMatcher
	Cond ExprMatcher
	Post StmtMatcher
	Body BlockStmtMatcher
}

// GoStmt
type zGoStmtMatcher struct {
	_ *ast.GoStmt

	Go   token.Pos
	Call CallExprMatcher
}

// IfStmt
type zIfStmtMatcher struct {
	_ *ast.IfStmt

	If   token.Pos
	Init StmtMatcher
	Cond ExprMatcher
	Body BlockStmtMatcher
	Else StmtMatcher
}

// IncDecStmt
type zIncDecStmtMatcher struct {
	_ *ast.IncDecStmt

	X      ExprMatcher
	TokPos token.Pos
	Tok    token.Token
}

// LabeledStmt
type zLabeledStmtMatcher struct {
	_ *ast.LabeledStmt

	Label IdentMatcher
	Colon token.Pos
	Stmt  StmtMatcher
}

// RangeStmt
type zRangeStmtMatcher struct {
	_ *ast.RangeStmt

	For    token.Pos
	Key    ExprMatcher
	Value  ExprMatcher
	TokPos token.Pos
	Tok    token.Token
	Range  token.Pos
	X      ExprMatcher
	Body   BlockStmtMatcher
}

// ReturnStmt
type zReturnStmtMatcher struct {
	_ *ast.ReturnStmt

	Return  token.Pos
	Results ExprListMatcher
}

// SelectStmt
type zSelectStmtMatcher struct {
	_ *ast.SelectStmt

	Select token.Pos
	Body   BlockStmtMatcher
}

// SendStmt
type zSendStmtMatcher struct {
	_ *ast.SendStmt

	Chan  ExprMatcher
	Arrow token.Pos
	Value ExprMatcher
}

// SwitchStmt
type zSwitchStmtMatcher struct {
	_ *ast.SwitchStmt

	Switch token.Pos
	Init   StmtMatcher
	Tag    ExprMatcher
	Body   BlockStmtMatcher
}

// TypeSwitchStmt
type zTypeSwitchStmtMatcher struct {
	_ *ast.TypeSwitchStmt

	Switch token.Pos
	Init   StmtMatcher
	Assign StmtMatcher
	Body   BlockStmtMatcher
}
