//go:build !genz

// Code generated by genz codez-matchers. DO NOT EDIT.

package codez

import (
	ast "go/ast"
	token "go/token"
)

// FuncDecl
type FuncDeclMatcherB struct {
	_ *ast.FuncDecl

	Doc  CommentGroupMatcher
	Recv FieldListMatcher
	Name IdentMatcher
	Type FuncTypeMatcher
	Body BlockStmtMatcher
}

func (m FuncDeclMatcherB) MatchDecl(cx *MatchContext, node ast.Decl) (ok bool, err error) {
	return m.Match(cx, node)
}
func (m FuncDeclMatcherB) Match(cx *MatchContext, node ast.Node) (ok bool, err error) {
	x, ok := node.(*ast.FuncDecl)
	if !ok {
		return false, nil
	}
	ok, err = match(cx, ok, err, m.Doc, x.Doc)
	ok, err = match(cx, ok, err, m.Recv, x.Recv)
	ok, err = match(cx, ok, err, m.Name, x.Name)
	ok, err = match(cx, ok, err, m.Type, x.Type)
	ok, err = match(cx, ok, err, m.Body, x.Body)
	return ok, err
}

// GenDecl
type GenDeclMatcherB struct {
	_ *ast.GenDecl

	Doc    CommentGroupMatcher
	TokPos token.Pos
	Tok    token.Token
	Lparen token.Pos
	Specs  ListMatcher[ast.Spec]
	Rparen token.Pos
}

func (m GenDeclMatcherB) MatchDecl(cx *MatchContext, node ast.Decl) (ok bool, err error) {
	return m.Match(cx, node)
}
func (m GenDeclMatcherB) Match(cx *MatchContext, node ast.Node) (ok bool, err error) {
	x, ok := node.(*ast.GenDecl)
	if !ok {
		return false, nil
	}
	ok, err = match(cx, ok, err, m.Doc, x.Doc)
	ok, err = matchList(cx, ok, err, m.Specs, x.Specs)
	return ok, err
}
