//go:build !genz

// Code generated by genz codez-matchers. DO NOT EDIT.

package codez

import (
	ast "go/ast"
	token "go/token"
)

// BadDecl
type zBadDeclMatcher struct {
	_ *ast.BadDecl

	From token.Pos
	To   token.Pos
}

// FuncDecl
type zFuncDeclMatcher struct {
	_ *ast.FuncDecl

	Doc  CommentGroupMatcher
	Recv FieldListMatcher
	Name IdentMatcher
	Type FuncTypeMatcher
	Body BlockStmtMatcher
}

// GenDecl
type zGenDeclMatcher struct {
	_ *ast.GenDecl

	Doc    CommentGroupMatcher
	TokPos token.Pos
	Tok    token.Token
	Lparen token.Pos
	Specs  SpecListMatcher
	Rparen token.Pos
}
