//go:build !genz

// Code generated by genz codez-matchers. DO NOT EDIT.

package codez

import (
	ast "go/ast"
	token "go/token"
)

// ArrayType
type ArrayTypeMatcher struct {
	_ *ast.ArrayType

	Lbrack token.Pos
	Len    ExprMatcher
	Elt    ExprMatcher
}

// BadExpr
type BadExprMatcher struct {
	_ *ast.BadExpr

	From token.Pos
	To   token.Pos
}

// BasicLit
type BasicLitMatcher struct {
	_ *ast.BasicLit

	ValuePos token.Pos
	Kind     token.Token
	Value    StringMatcher
}

// BinaryExpr
type BinaryExprMatcher struct {
	_ *ast.BinaryExpr

	X     ExprMatcher
	OpPos token.Pos
	Op    token.Token
	Y     ExprMatcher
}

// CallExpr
type CallExprMatcher struct {
	_ *ast.CallExpr

	Fun      ExprMatcher
	Lparen   token.Pos
	Args     ExprListMatcher
	Ellipsis token.Pos
	Rparen   token.Pos
}

// ChanType
type ChanTypeMatcher struct {
	_ *ast.ChanType

	Begin token.Pos
	Arrow token.Pos
	Dir   ChanDirMatcher
	Value ExprMatcher
}

// CompositeLit
type CompositeLitMatcher struct {
	_ *ast.CompositeLit

	Type       ExprMatcher
	Lbrace     token.Pos
	Elts       ExprListMatcher
	Rbrace     token.Pos
	Incomplete BoolMatcher
}

// Ellipsis
type EllipsisMatcher struct {
	_ *ast.Ellipsis

	Ellipsis token.Pos
	Elt      ExprMatcher
}

// FuncLit
type FuncLitMatcher struct {
	_ *ast.FuncLit

	Type FuncTypeMatcher
	Body BlockStmtMatcher
}

// FuncType
type FuncTypeMatcher struct {
	_ *ast.FuncType

	Func       token.Pos
	TypeParams FieldListMatcher
	Params     FieldListMatcher
	Results    FieldListMatcher
}

// Ident
type IdentMatcher struct {
	_ *ast.Ident

	NamePos token.Pos
	Name    StringMatcher
	Obj     ObjectMatcher
}

// IndexExpr
type IndexExprMatcher struct {
	_ *ast.IndexExpr

	X      ExprMatcher
	Lbrack token.Pos
	Index  ExprMatcher
	Rbrack token.Pos
}

// IndexListExpr
type IndexListExprMatcher struct {
	_ *ast.IndexListExpr

	X       ExprMatcher
	Lbrack  token.Pos
	Indices ExprListMatcher
	Rbrack  token.Pos
}

// InterfaceType
type InterfaceTypeMatcher struct {
	_ *ast.InterfaceType

	Interface  token.Pos
	Methods    FieldListMatcher
	Incomplete BoolMatcher
}

// KeyValueExpr
type KeyValueExprMatcher struct {
	_ *ast.KeyValueExpr

	Key   ExprMatcher
	Colon token.Pos
	Value ExprMatcher
}

// MapType
type MapTypeMatcher struct {
	_ *ast.MapType

	Map   token.Pos
	Key   ExprMatcher
	Value ExprMatcher
}

// ParenExpr
type ParenExprMatcher struct {
	_ *ast.ParenExpr

	Lparen token.Pos
	X      ExprMatcher
	Rparen token.Pos
}

// SelectorExpr
type SelectorExprMatcher struct {
	_ *ast.SelectorExpr

	X   ExprMatcher
	Sel IdentMatcher
}

// SliceExpr
type SliceExprMatcher struct {
	_ *ast.SliceExpr

	X      ExprMatcher
	Lbrack token.Pos
	Low    ExprMatcher
	High   ExprMatcher
	Max    ExprMatcher
	Slice3 BoolMatcher
	Rbrack token.Pos
}

// StarExpr
type StarExprMatcher struct {
	_ *ast.StarExpr

	Star token.Pos
	X    ExprMatcher
}

// StructType
type StructTypeMatcher struct {
	_ *ast.StructType

	Struct     token.Pos
	Fields     FieldListMatcher
	Incomplete BoolMatcher
}

// TypeAssertExpr
type TypeAssertExprMatcher struct {
	_ *ast.TypeAssertExpr

	X      ExprMatcher
	Lparen token.Pos
	Type   ExprMatcher
	Rparen token.Pos
}

// UnaryExpr
type UnaryExprMatcher struct {
	_ *ast.UnaryExpr

	OpPos token.Pos
	Op    token.Token
	X     ExprMatcher
}
